version: '3'
services:

  rabbitmq_server:
    image: "rabbitmq:3.6.10-alpine"
    environment:
      - HOSTNAME=localhost
      - RABBITMQ_NODE_IP_ADDRESS=172.18.0.2
      - RABBITMQ_NODE_PORT=5672

  rabbitmq_management:
    image: "rabbitmq:3-management"
    depends_on:
      - rabbitmq_server

  mongo_server:
    image: "mongo:3.5"
    environment:
      - MONGODB_HOST=172.18.0.3
    expose:
      - "27017"

  receiver_mail:
    depends_on:
      - mongo_server
      - rabbitmq_server
    image: zedesk/zdknode:8.0.0
    volumes:
      - ./receiver_mail:/app
    ports:
      - 8200:8080
    environment:
      - MONGO_HOST=172.18.0.3
      - RABBIT_HOST=172.18.0.2
    command: ["run", "dev"]

  receiver_sms:
    depends_on:
      - mongo_server
      - rabbitmq_server
    image: zedesk/zdknode:8.0.0
    volumes:
      - ./receiver_sms:/app
    ports:
      - 8201:8080
    environment:
      - MONGO_HOST=172.18.0.3
      - RABBIT_HOST=172.18.0.2
    command: ["run", "dev"]

  sender:
    depends_on:
      - mongo_server
      - rabbitmq_server
      - receiver_mail
      - receiver_sms
    image: zedesk/zdknode:8.0.0
    volumes:
      - ./sender:/app
    ports:
      - 8202:8080
    environment:
      - MONGO_HOST=172.18.0.3
      - RABBIT_HOST=172.18.0.2
    command: ["run", "dev"]