version: '3'
services:

  # The RabbitMQ service, to be able to communicate as a MOM with AMQP to the others containers (micro-services)
  rabbitmq:
    image: "rabbitmq:3.6.10-alpine"
    environment:
      - HOSTNAME=localhost
      - RABBITMQ_NODE_PORT=5672
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"

  # The script charged to receive and handle messages targeted to the 'MAIL' queue
  receiver-mail:
    depends_on:
      - rabbitmq
    image: zedesk/zdknode:8.0.0
    volumes:
      - ./receiver_mail:/app
    environment:
      - QUEUE_SERVER=0.0.0.0
    command: ["run", "dev"]

#  # The script charged to receive and handle messages targeted to the 'SMS' queue
#  receiver-sms:
#    depends_on:
#      - rabbitmq
#    image: zedesk/zdknode:8.0.0
#    volumes:
#      - ./receiver_sms:/app
#    environment:
#      - QUEUE_SERVER=localhost
#    command: ["run", "dev"]
#
#  # The script charged to send the message through the MOM
#  sender:
#    depends_on:
#      - rabbitmq
#      - receiver-mail
#      - receiver-sms
#    image: zedesk/zdknode:8.0.0
#    volumes:
#      - ./sender:/app
#    environment:
#      - QUEUE_SERVER=localhost
#    command: ["run", "dev"]