version: '3'
services:

  mongo_server:
    image: "mongo:3.5"
    expose:
      - "27017"

  receiver_mail:
    depends_on:
      - mongo_server
    image: zedesk/zdknode:8.0.0
    volumes:
      - ./receiver_mail:/app
    ports:
      - 8200:8080
    environment:
      - MONGO_HOST=172.18.0.2
    command: ["run", "dev"]

  receiver_sms:
    depends_on:
      - mongo_server
    image: zedesk/zdknode:8.0.0
    volumes:
      - ./receiver_sms:/app
    ports:
      - 8201:8080
    environment:
      - MONGO_HOST=172.18.0.2
    command: ["run", "dev"]

  sender:
    depends_on:
      - mongo_server
      - receiver_mail
      - receiver_sms
    image: zedesk/zdknode:8.0.0
    volumes:
      - ./sender:/app
    ports:
      - 8202:8080
    environment:
      - MONGO_HOST=172.18.0.2
    command: ["run", "dev"]